services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres-db
      - frontend
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5432/class_schedule_db
      POSTGRES_DB: class_schedule_db
      POSTGRES_USER: class_schedule_dbuser
      POSTGRES_PASSWORD: Qazxcd123
      REDIS_ADDRESS: redis://redis:6379
    networks:
      - network1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - network1

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: class_schedule_db
      POSTGRES_USER: class_schedule_dbuser
      POSTGRES_PASSWORD: Qazxcd123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  db_data:

networks:
  network1:
    driver: bridge